version: 2
updates:
  - package-ecosystem: "maven"
    directory: "json-smart"
    schedule:
      interval: "monthly"
  - package-ecosystem: "maven"
    directory: "json-smart-action"
    schedule:
      interval: "monthly"
